server:
      port: 8099  #配置端口
      address : localhost
      connection-timeout: 30
      tomcat.max-threads: 0
      tomcat.uri-encoding: UTF-8
      servlet:
                session:
                          timeout: 30


spring:
      devtools:
              restart:
                      enabled: true #热部署生效
                      additional-paths: spring-boot-rocketmq1/src/main/java  #设置重启的目录
#                      exclude: WEB-INF/**   #classpath目录下的WEB-INF文件夹内容修改不重启


# LOGGING
logging:
        level:
              root: INFO
              org:
                  springframework: DEBUG
                  hibernate: DEBUG
#        path: F:\\
#        file: log.log
              com:
                  ibatis: DEBUG
                  abin:
                        lee:
                            spring:
                                      boot:
                                              rocketmq:  DEBUG




debug: true













